config/routes.rb
Rails.application.routes.draw do
  root :to=> "pages#home"

  devise_for :users
  resources :tickets
  resources :events, :only => [:index, :new, :create, :show]

  get '/charge', to: 'payment#charge'
  get '/purchase', to: 'tickets#purchase'
  post '/charge', to: 'payment#charged'
  post '/purchase', to: 'tickets#purchaseTickets'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :artist, :presence => true
  validates :description, :presence => true
  validates :price_low, :presence => true
  validates :price_high, :presence => true
  validates :event_date, :presence => true
  has_many :tickets
  def event_date_not_from_past
    if event_date < Date.today
      errors.add('Data wydarzenia', 'nie może być z przeszłości')
    end
  end
  validates :seats_rows, :presence => {:message => 'Podaj ilość rzędów'}
  validates :seats_columns, :presence => {:message => 'Podaj ilość miejsc w rzędzie'}

  def is_seat_available(seat_id)
    !tickets.map {|ticket| ticket.seat_id_seq}.include? seat_id
  end


  def get_seat_price(row, col)
    if row > (seats_rows / 2)
      return price_low
    end
    if col < (seats_columns / 4) || col > (3 * seats_columns / 4)
      return (price_low + price_high) / 2
    end
    return price_high
  end

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  validates :name, :presence => true,
            :length => {:minimum => 6}
  validates :email_address, :presence => true
  validates :price, :presence => true
  validates :phone, :presence => true,
            :length => {:minimum => 6},
            :numericality => true
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
  class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tickets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:komunikat] = 'Event został poprawnie stworzony.'
      redirect_to "/events/#{@event.id}"
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:artist, :description, :price_low, :price_high, :event_date, :seats_rows, :seats_columns, :isForAdults)
  end
end

app/controllers/payment_controller.rb
class PaymentController < ApplicationController
  def charged
    @user = current_user
    amount = params[:amount]
    new_balance = @user.founds + amount.to_d
    if @user.update_attribute(:founds, new_balance)
      respond_to do |format|
        format.html {redirect_to '/', notice: 'Konto zostało zasilone środkami'}
      end
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  include EventsHelper, TicketsHelper
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  def purchase
  end


  # POST /tickets
  # POST /tickets.json
  def create
    user = current_user
    seats = ticket_params[:seat_id_seq].gsub(/\s+/m, ' ').strip.split(" ")
    name = ticket_params[:name]
    address = ticket_params[:address]
    price = ticket_params[:price]
    email_address = ticket_params[:email_address]
    phone = ticket_params[:phone]
    event_id = ticket_params[:event_id]
    user_id = user.id
    counter = 0
    event = get_event(event_id)
    max_tickets = 5 - get_current_user_tickets(event.tickets).length
    seats.each do |seat|
      if counter >= max_tickets
        raise "Limit biletów na wydarzenie został wykorzystany";
      end

      if price.to_d > user.founds
        raise "Brak wystarczających środków na koncie"
      end

      @ticket = Ticket.new({:seat_id_seq => seat, :event_id => event_id, :name => name, :email_address => email_address, :phone => phone, :user_id => user_id, :price => price, :address => address})
      if @ticket.save
        counter += 1
      else
        raise @ticket.errors.full_messages.inspect
      end
    end
    new_balance = user.founds - @ticket.price
    user.update_attribute(:founds, new_balance)
    respond_to do |format|
      format.html {redirect_to tickets_url, notice: 'Bilety zostały zamówione'}
      format.json {head :no_content}
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end


  def correct_user
    if current_user&.isAdmin
      return
    end
    @ticket = current_user.tickets.find_by(id: params[:id])
    redirect_to tickets_path, notice: "Nie jesteś uprawniony do edycji tego biletu" if @ticket.nil?
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:name, :seat_id_seq, :address, :price, :email_address, :phone, :event_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def get_event(event_id)
    Event.find_by(:id => event_id)
  end

  def get_seat_id(row, col)
    (64 + row).chr + col.to_s
  end
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def get_current_user_tickets(tickets)
    if current_user&.isAdmin
      return tickets
    end
    tickets.select {|ticket| ticket.user_id == current_user.id}
  end

  def determine_ticket_price(event_id)
    event = Event.find(event_id)
    price = event.price_low
    price
  end

end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row field">
  <div class="col-md-2">
    <%= form.label "Artysta" %>
  </div>
  <div class="col-md-10">
    <%= form.text_field :artist, id: :event_artist, class: "w-100" %>
  </div>
  </div>

  <div class="row field">
    <div class="col-md-2">
      <%= form.label "Opis" %>
    </div>
    <div class="col-md-10">
      <%= form.text_field :description, id: :event_description,  class: "w-100" %>
    </div>
  </div>

  <div class="row field">
    <div class="col-md-2">
      <%= form.label "Cena od" %>
    </div>
    <div class="col-md-10">
      <%= form.text_field :price_low, id: :event_price_low,  class: "w-100" %>
    </div>
  </div>


  <div class="row field">
    <div class="col-md-2">
      <%= form.label "Cena do" %>
    </div>
    <div class="col-md-10">
      <%= form.text_field :price_high, id: :event_price_high,  class: "w-100" %>
    </div>
  </div>

  <div class="row field">
    <div class="col-md-2">
      <%= form.label "Data wydarzenia" %>
    </div>
    <div class="col-md-10">
      <%= form.text_field :event_date, id: :event_event_date %>
    </div>
  </div>

  <div class="row field">
    <div class="col-md-2">
      <%= form.label "Liczba rzędów" %>
    </div>
    <div class="col-md-10">
      <%= form.text_field :seats_rows, id: :event_seats_rows %>
    </div>
  </div>

  <div class="row field">
    <div class="col-md-2">
      <%= form.label "Liczba siedzeń w rzędzie" %>
    </div>
    <div class="col-md-10">
      <%= form.text_field :seats_columns, id: :event_seats_columns %>
    </div>
  </div>

  <div class="row field">
    <div class="col-md-2">
      <%= form.label "Tylko dla dorosłych?" %>
    </div>
    <div class="col-md-10">
      <%= form.check_box :isForAdults, id: :event_isForAdults %>
    </div>
  </div>


  <div class="actions float-right">
    <%= form.submit "Utwórz wydarzenie", class: "btn btn-success" %>
  </div>
<% end %>

app/views/events/_tickets_list.html.erb
<h1>Bilety</h1>

<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Seat id seq</th>
    <th>Address</th>
    <th>Price</th>
    <th>Email address</th>
    <th>Phone</th>
    <th>Event</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% tickets.each do |ticket| %>
    <tr>
      <td><%= ticket.name %></td>
      <td><%= ticket.seat_id_seq %></td>
      <td><%= ticket.address %></td>
      <td><%= ticket.price %></td>
      <td><%= ticket.email_address %></td>
      <td><%= ticket.phone %></td>
      <td><%= ticket.event_id %></td>
      <td><%= link_to 'Pokaż', ticket %></td>
      <td><%= link_to 'Edytuj', edit_ticket_path(ticket) %></td>
      <td><%= link_to 'Usuń', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/events/index.html.erb
<ul>
  <% for event in @events %>
    <div class="list-group">
      <a href="/events/<%=event.id %>" class="list-group-item list-group-item-info">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="text-muted"><%=event.artist %></h5>
          <small class="text-muted"><%=event.event_date %></small>
        </div>
        <p class="text-muted"><%=event.description %></p>
      </a>
      <hr>
    </div>
  <% end %>
</ul>
<br>
<% if current_user&.isAdmin? %>
  <%= link_to 'Nowe wydarzenie', new_event_path, {:class => "btn btn-dark float-right"} %>
<% end %>

app/views/events/new.html.erb
<h1>Nowe wydarzenie</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="message"><%= flash[:message] %></p>

<h2 class="mb-5"><%= @event.artist %></h2>

<div class="col-md-10">

  <h6>
    <%= @event.description %>
  </h6>

  <hr>

  <h6>
    <strong>Bilety od </strong> <%= @event.price_low %> <strong> do </strong>     <%= @event.price_high %>
  </h6>

  <h6>
    <strong>Ilość miejsc:</strong>
    <%= @event.seats_rows * @event.seats_columns %>
  </h6>

  <h6>
    <strong>Data:</strong>
    <%= @event.event_date %>
  </h6>

  <h6>
    <% if @event.isForAdults? %>
      <strong>TYLKO DLA DOROSLYCH:</strong>
    <% else %>
      <strong>BRAK OGRANICZEŃ WIEKOWYCH:</strong>
    <% end %>
  </h6>
</div>

<hr>

<div class="text-center">
  <h2>Dostępne miejsca </h2>
</div>
<div class="top-mg-50">
  <% width = 100 / @event.seats_columns %>
  <% for i in 1..@event.seats_rows do %>
    <div class="row">
      <% for j in 1..@event.seats_columns do %>
        <% seat = get_seat_id(i, j) %>
        <% seat_price = @event.get_seat_price(i, j) %>
        <a
        class="text-white btn
          <%= @event.is_seat_available(seat) ? 'btn btn-success btn-sm seat_icon' : 'btn-danger btn-sm seat_icon' %>"
        style="padding: 15px 0; width : <%= width %>%;
            <% if j < @event.seats_columns %>
            border-right: 1px solid #fff;
            <% end %>
            <% if i < @event.seats_rows %>
            border-bottom: 1px solid #fff;
          <% end %>">

          <%= seat %> [ <%= seat_price.to_d %> PLN]
        </a>
      <% end %>
    </div>
  <% end %>
</div>

<% if user_signed_in? %>
  <div class="top-mg-50">
    <div class="row">
      <div class="offset-8 col-md-4">
        <button class="btn btn-warning w-100" id="buy_marked_tickets">Kup bilety</button>
      </div>
    </div>
  </div>
<% end %>

<br>

<% if current_user&.isAdmin? %>
  <%= render "tickets_list", tickets: @event.tickets %>
<% end %>

<% if user_signed_in? %>
  <div id="max-tickets" style="display: none">
    <%= 5 - get_current_user_tickets(@event.tickets).length %>
  </div>
  <div id="user-founds" style="display: none">
    <%= current_user.founds %>
  </div>
  <%= javascript_include_tag 'SeatsMap/seatsMaper', 'data-turbolinks-track': 'reload' %>
<% end %>

<%= link_to 'Powrót', events_path, :class => "btn btn-success" %>
<br>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg bg-dark row fixed-top">
    <div class = "col-md-3 ">
      <a class="navbar-brand " href="/">
        <i class="fa fa-address-book-o"></i>
        Biletex
      </a>
    </div>
    <div class="col-md-5 offset-md-4">
      <ul class="navbar-nav float-right center ">
        <li class="nav-item ">
          <a class="nav-link" href="/events">Wydarzenia</a>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link" href="/tickets">Bilety</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/charge">Zasil konto [<%= current_user.founds %> PLN]</a>
          </li>
        <% end %>
        <hr>
        <% if user_signed_in? %>
          <li class="nav-item">
          <%= link_to "Wyloguj [" + current_user.email + "]", destroy_user_session_path, method: :delete, :class => 'nav-link'
          %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Zaloguj się", new_user_session_path, :class => 'nav-link' %>
          </li>
          <li class="nav-item">
          <%= link_to "Zarejestruj się", new_user_registration_path, :class => 'nav-link' %> <br>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bilety</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render 'layouts/header' %>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <div class="container wrapper">
    <%= yield %>
  </div>
  </body>
</html>

app/views/payment/charge.html.erb
<div class="container" align="center">
<h1>Doładuj sie</h1>
  <br>

<hr>
<div class="top-mg-50">
  <h3>Stan konta: <%= current_user.founds.to_d %> PLN </h3>
</div>
  <br>

  <hr>
<div class="form-wrapper">
  <%= form_tag('/charge', method: 'post') do %>
    <%= label_tag "Kwota doładowania" %><br>
    <%= text_field_tag :amount %>

    <div class="actions ">
      <%= submit_tag "Zatwierdź", class: "btn btn-success" %>
    </div>
  <% end %>
</div>
</div>

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :ticket_name %>
  </div>

  <div class="field">
    <%= form.label :seat_id_seq %>
    <%= form.text_field :seat_id_seq, id: :ticket_seat_id_seq %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, id: :ticket_address %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :ticket_price %>
  </div>

  <div class="field">
    <%= form.label :email_address %>
    <%= form.text_field :email_address, id: :ticket_email_address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :ticket_phone %>
  </div>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.text_field :event_id, id: :ticket_event_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/_new_ticket.html.erb
<div class="container">
  <h2>Uzupełnij swoje dane </h2>
  <hr>
  <%= form_with(model: ticket, local: true) do |form| %>
    <% if ticket.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

        <ul>
          <% ticket.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
      <div class="col-md-2">
        <%= form.label "Nazwa" %>
      </div>
      <div class="col-md-6">
        <%= form.text_field :name, id: :ticket_name, :class => "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= form.label "Adres" %>
      </div>
      <div class="col-md-6">
        <%= form.text_area :address, id: :ticket_address, :class => "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= form.label "Identyfikatory miejsc" %>
      </div>
      <div class="col-md-6">
        <%= form.text_field :seat_id_seq, id: :ticket_seat_id_seq, value: seats, :readonly => true, :class => "form-control" %>
      </div>
    </div>


    <div class="row">
      <div class="col-md-2">
        <%= form.label "Cena [zł]" %>
      </div>
      <div class="col-md-6">
        <%= form.text_field :price, id: :ticket_price, value: tickets_price, :readonly => true, :class => "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= form.label "Adres email" %>
      </div>
      <div class="col-md-6">
        <%= form.text_field :email_address, id: :ticket_email_address, :class => "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <%= form.label "Telefon" %>
      </div>
      <div class="col-md-6">
        <%= form.text_field :phone, id: :ticket_phone, :class => "form-control" %>
      </div>
    </div>

    <% if ticket.event_id? %>
      <%= form.hidden_field :event_id, id: :ticket_event_id, value: ticket.event_id %>
    <% end %>

    <div class="actions">
      <%= form.submit "Kup bilety", :class => "btn-lg btn-success" %>
    </div>
  <% end %>
</div>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bilety</h1>



<table class="table">
  <thead>
    <tr>
      <th>Nazwa</th>
      <th>Identyfikator miejsca</th>
      <th>Adres</th>
      <th>Cena</th>
      <th>Email</th>
      <th>Numer telefonu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
    <% if ticket.user == current_user || current_user&.isAdmin %>
        <td><%= ticket.name %></td>
        <td><%= ticket.seat_id_seq %></td>
        <td><%= ticket.address %></td>
        <td><%= ticket.price %></td>
        <td><%= ticket.email_address %></td>
        <td><%= ticket.phone %></td>
        <td><%= link_to 'Pokaż', ticket %></td>
        <% if current_user&.isAdmin %>
          <td><%= link_to 'Edytuj', edit_ticket_path(ticket) %></td>
          <td><%= link_to 'Usuń', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
    <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/purchase.html.erb
<% seats = params[:seat_ids] %>
<% event_id = params[:event_id] %>
<% tickets_price = params[:tickets_price] %>
<% if user_signed_in? %>
  <%= render "new_ticket", ticket: Ticket.new( :event_id=>event_id), seats: seats, tickets_price: tickets_price%>
<% end %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ticket.name %>
</p>

<p>
  <strong>Seat id seq:</strong>
  <%= @ticket.seat_id_seq %>
</p>

<p>
  <strong>Address:</strong>
  <%= @ticket.address %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ticket.price %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @ticket.email_address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @ticket.phone %>
</p>

<p>
  <strong>Event:</strong>
  <%= @ticket.event_id %>
</p>

<% if current_user&.isAdmin %>
   <%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<% end %>
<%= link_to 'Back', tickets_path %>